# Generated by Django 5.0.1 on 2026-01-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg1_new_beds',
            name='bed_code',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pg1_new_beds',
            name='roon_no',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room_pg1',
            name='roon_no',
            field=models.FloatField(),
        ),
    ]
