# Generated by Django 5.0.1 on 2026-01-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch1app', '0002_alter_pg1_new_beds_bed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg1_new_beds',
            name='bed_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pg1_new_beds',
            name='roon_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room_pg1',
            name='roon_no',
            field=models.IntegerField(),
        ),
    ]
