# Generated by Django 5.0.1 on 2026-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch6app', '0002_alter_pg1_new_beds_bed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg1_new_guest',
            name='bed_code',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pg1_new_guest',
            name='roon_no',
            field=models.FloatField(),
        ),
    ]
