# Generated by Django 5.0.1 on 2026-09-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_amount_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('particulars', models.CharField(max_length=250)),
                ('transaction_amount', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('transaction_enter_date', models.CharField(max_length=250)),
                ('transaction_enter_time', models.CharField(max_length=250)),
                ('month', models.CharField(max_length=20)),
                ('transaction_updated_date', models.CharField(max_length=250)),
                ('transaction_updated_time', models.CharField(max_length=250)),
                ('enter_by', models.CharField(max_length=200)),
                ('cb_date', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('ub_date', models.CharField(max_length=200)),
                ('deleted_by', models.CharField(max_length=200)),
                ('db_date', models.CharField(max_length=200)),
                ('ub_flag', models.IntegerField()),
                ('flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='member_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('sum_amt', models.CharField(max_length=250)),
                ('enter_by', models.CharField(max_length=200)),
                ('cb_date', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('ub_date', models.CharField(max_length=200)),
                ('deleted_by', models.CharField(max_length=200)),
                ('db_date', models.CharField(max_length=200)),
                ('ub_flag', models.IntegerField()),
                ('member_flag', models.IntegerField()),
            ],
        ),
    ]
