# Generated by Django 5.0.1 on 2026-02-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0002_ledgerentrybackups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
