# Generated by Django 5.0.1 on 2026-02-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0003_alter_ledgerentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentrybackups',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentrybackups',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ledgerentrybackups',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
