# Generated by Django 5.0.1 on 2026-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0004_alter_ledgerentrybackups_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='entry_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
