# Generated by Django 5.0.1 on 2026-02-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0005_ledgerentry_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentrybackups',
            name='entry_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
