# Generated by Django 5.0.1 on 2026-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0006_ledgerentrybackups_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ledgerentrybackups',
            name='entry_id',
            field=models.CharField(max_length=200),
        ),
    ]
